version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target/site
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "lamahmichelmarie@gmail.com"
            git config user.name "MichelMarieLamah13"
      - add_ssh_keys:
          fingerprints:
            - "6a:fc:62:92:cc:60:42:b4:3f:2b:8a:e1:d2:c7:5c:f9"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist target/site/apidocs
workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - build-and-test
          filters:
              branches:
                only: master

